############################################################
# Dockerfile to build the kannji redmine image
# Based on redmine
############################################################
FROM owncloud
LABEL maintainer "Jan-Luca Klees"

COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh